# Generated by Django 5.2.6 on 2026-02-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tagged In',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='photos/originals/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='photos/thumbnails/')),
                ('watermarked_image', models.ImageField(blank=True, null=True, upload_to='photos/watermarked/')),
                ('exif_data', models.JSONField(blank=True, null=True)),
                ('ai_tags', models.JSONField(blank=True, null=True)),
                ('manual_tags', models.JSONField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='events.event')),
            ],
        ),
    ]
